name: presensikita
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.14.0
  flutterfire_cli: 0.2.7
  cloud_firestore: 4.8.2
  firebase_storage: 11.2.4
  firebase_auth: 4.6.3
  image_picker: 1.0.1
  convex_bottom_bar: 3.2.0
  intl: 0.18.1
  geolocator: 9.0.2
  geocoding: 2.1.0
  syncfusion_flutter_datepicker: 22.1.39
  flutter: 
    sdk: flutter
  


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_launcher_icons: "^0.10.0"
  flutter_test: 
    sdk: flutter



flutter: 
  uses-material-design: true

